In [7]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
with open("../data/dataset.csv", "r") as fin:
    data=[]
    for line in fin:
        data.append(line.strip())
data=np.array(data, dtype="float32")
data

array([ 99., 212.,  49., ..., 217., 164., 132.], dtype=float32)

In [13]:
num,count=np.unique(data, return_index=False, return_inverse=False, return_counts=True, axis=None)
count

array([14, 18, 19, 10, 18, 12, 14, 16, 24, 17, 16, 18, 15, 15, 26, 13, 18,
       22, 13, 15, 17, 16, 11, 10, 16, 15, 15, 16, 10, 22, 11, 10, 14, 18,
        9, 16, 18, 19, 15, 25, 15, 21, 17, 13, 19,  9,  8, 21, 20, 10, 10,
       21, 19, 18, 24, 15, 11, 10, 18, 23, 19, 13, 20, 17, 15, 17, 16, 16,
       19, 17, 18, 19, 23, 13, 12, 15, 19, 21, 24, 15, 18, 15, 22, 22, 18,
       12, 13, 15, 18, 19, 21, 17, 16, 13, 17,  7, 15, 19, 13, 19, 16, 12,
       14, 16, 21, 16, 18, 19, 17, 13, 17, 14, 18, 20, 18, 13, 15, 21, 21,
       16, 17, 22, 18, 15, 12, 14, 15, 15, 26, 10, 17, 16, 20, 23, 21, 19,
       21, 18, 21, 16, 25, 25, 17, 25, 15, 16, 17, 27, 16, 13, 13, 18, 15,
       12, 22, 16, 15, 17,  8, 13, 19, 13, 20, 16, 11, 23, 17, 20, 22, 17,
       30, 16, 18, 12, 13, 21, 12, 14,  7, 19, 17, 16, 15, 12, 17, 21, 12,
       16, 19, 21, 11,  8, 14, 19, 13, 15,  4, 18, 20, 17, 14, 19, 13, 17,
       16, 22, 19, 20, 17, 12, 17, 24, 18, 18, 15, 20, 14, 15, 14,  8, 18,
       17, 17, 22, 16, 21

In [14]:
sum(count)

4000

In [15]:
sum_=0
for el in count:
    sum_+= (el**2)
sum_    

70618

In [28]:
#print(np.argsort(count))
l=count[np.argsort(count)]
l

array([ 4,  7,  7,  8,  8,  8,  8,  9,  9, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
       12, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
       13, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15,
       15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
       15, 15, 15, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
       16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17, 17,
       17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
       17, 17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
       18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 19, 19,
       19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19,
       19, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 21, 21, 21, 21, 21, 21,
       21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 22, 22, 22, 22, 22, 22, 22,
       22, 22, 22, 23, 23

In [39]:
most_ferquent_sum=sum(l[:-36])
most_ferquent_sum

3173

In [33]:

most_ferquent_sum=0
for el in l[:-36]:
    most_ferquent_sum+=(el**2)
    
print(most_ferquent_sum)    




51467


In [37]:
np.linalg.norm(l[:-36])

226.86339501999876